version: 1.0.{build}
configuration:
- Debug
- Release
platform: Any CPU
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
cache: '%USERPROFILE%\.nuget\packages'
before_build:
- cmd: dotnet restore
- ps: >-
    Get-ChildItem -Path $ENV:APPVEYOR_BUILD_FOLDER -Recurse –File -Filter project.json | foreach {
      $jsonFile = Get-Content $_.FullName -raw | ConvertFrom-Json
      if($jsonFile.version)
      {
          $jsonFile.version = $ENV:APPVEYOR_BUILD_VERSION
          $jsonFile | ConvertTo-Json -Depth 999 | Out-File $_.FullName
      }
    }
build:
  verbosity: normal
after_build:
- dotnet pack "src\utes.Xunit" -c %CONFIGURATION% --no-build --version-suffix %APPVEYOR_BUILD_VERSION% -o artifacts
test_script:
- ps: >-
    $ENV:USERPROFILE\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe "-target:C:\Program Files\dotnet\dotnet.exe" -targetargs:" test ""$ENV:APPVEYOR_BUILD_FOLDER\tests\utes.Core.Tests"" -c $ENV:CONFIGURATION" -register:user "-filter:+[utes.Core*]* -[utes.Core.Tests]*" -output:results.xml -oldStyle

    $ENV:USERPROFILE\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe "-target:C:\Program Files\dotnet\dotnet.exe" -targetargs:" test ""$ENV:APPVEYOR_BUILD_FOLDER\tests\utes.WebApplicationAssemblyStorage.Tests"" -c $ENV:CONFIGURATION" -register:user "-filter:+[utes.WebApplicationAssemblyStorage*]* -[utes.WebApplicationAssemblyStorage.Tests]*" -output:results.xml -mergeoutput -oldStyle

    $ENV:PATH=C:\\Python34;C:\\Python34\\Scripts;$ENV:PATH

    pip install git+git://github.com/codecov/codecov-python.git

    codecov -f "results.xml"
artifacts:
- path: artifacts\**\*.*
