version: 0.0.{build}
configuration:
- Debug
- Release
platform: Any CPU
init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
cache: '%USERPROFILE%\.nuget\packages'
before_build:
- dotnet restore
build:
  verbosity: normal
after_build:
- dotnet pack "src\utes.Xunit" -c %CONFIGURATION% --no-build --version-suffix %LABEL% -o artifacts
test_script:
- dotnet test "tests\utes.Core.Tests" -c %CONFIGURATION%
artifacts:
- path: artifacts\**\*.*
