version: 1.0.{build}
configuration:
- Debug
- Release
platform: Any CPU
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
cache: '%USERPROFILE%\.nuget\packages'
init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
before_build:
- cmd: dotnet restore
- ps: >-
    Get-ChildItem -Path $ENV:APPVEYOR_BUILD_FOLDER -Recurse –File -Filter project.json | foreach {
      $jsonFile = Get-Content $_.FullName -raw | ConvertFrom-Json
      if($jsonFile.version)
      {
          $jsonFile.version = $ENV:APPVEYOR_BUILD_VERSION
          $jsonFile | ConvertTo-Json -Depth 999 | Out-File $_.FullName
      }
    }
build:
  verbosity: normal
after_build:
- dotnet pack "src\utes.Xunit" -c %CONFIGURATION% --no-build --version-suffix %APPVEYOR_BUILD_VERSION% -o artifacts
test_script:
- ps: >-
    $ENV:USERPROFILE\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe
artifacts:
- path: artifacts\**\*.*
