//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace utes.WebApp.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AssemblyController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal AssemblyController() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("utes.WebApp.Resources.AssemblyController", typeof(AssemblyController).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The uploaded file is not valid..
        /// </summary>
        public static string ErrorHeadingExceptionAssemblyNotValid {
            get {
                return ResourceManager.GetString("ErrorHeadingExceptionAssemblyNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No assembly uploaded..
        /// </summary>
        public static string ErrorHeadingExceptionAssemblyUpload {
            get {
                return ResourceManager.GetString("ErrorHeadingExceptionAssemblyUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please upload a valid assembly file..
        /// </summary>
        public static string ErrorMessageExceptionAssemblyNotValid {
            get {
                return ResourceManager.GetString("ErrorMessageExceptionAssemblyNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Please upload a valid assembly file..
        /// </summary>
        public static string ErrorMessageExceptionAssemblyUpload {
            get {
                return ResourceManager.GetString("ErrorMessageExceptionAssemblyUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No assembly uploaded.
        /// </summary>
        public static string LogExceptionAssemblyUpload {
            get {
                return ResourceManager.GetString("LogExceptionAssemblyUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Assembly &apos;{0}&apos; successfully uploaded..
        /// </summary>
        public static string LogSucessfullyAssemblyUpload {
            get {
                return ResourceManager.GetString("LogSucessfullyAssemblyUpload", resourceCulture);
            }
        }
    }
}
